AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ses2Line

Globals:
  Function:
    Timeout: 3

Resources:
  lambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Environment:
        Variables:
          S3_BUCKET: !Ref mailBucket
  logGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${lambda}
      RetentionInDays: 14
  mailBucket:
    Type: AWS::S3::Bucket
